apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: convert-to-dpfm-invoice-document-from-self-invoice-edi-for-smes
  name: convert-to-dpfm-invoice-document-from-self-invoice-edi-for-smes
spec:
  replicas: 1
  selector:
    matchLabels:
      run: convert-to-dpfm-invoice-document-from-self-invoice-edi-for-smes
      app: CONVERT_TO_DPFM_INVOICE_DOCUMENT_FROM_SELF_INVOICE_EDI_FOR_SMES
  template:
    metadata:
      labels:
        run: convert-to-dpfm-invoice-document-from-self-invoice-edi-for-smes
        app: CONVERT_TO_DPFM_INVOICE_DOCUMENT_FROM_SELF_INVOICE_EDI_FOR_SMES
    spec:
      hostname: convert-to-dpfm-invoice-document-from-self-invoice-edi-for-smes
      containers:
        - name: convert-to-dpfm-invoice-document-from-self-invoice-edi-for-smes
          image: latonaio/convert-to-dpfm-invoice-document-from-self-invoice-edi-for-smes
          imagePullPolicy: Always
          env:
            - name: "RMQ_QUEUE_FROM"
              value: "convert-to-dpfm-invoice-document-from-self-invoice-edi-for-smes-queue"
            - name: "RMQ_QUEUE_TO"
              value: "data-platform-api-data-concatenation-queue"
            - name : "NESTJS_DATA_CONNECTION_REQUEST_CONTROL_MANAGER_CONSUME"
              value: "nestjs-data-connection-request-control-manager-consume"
            - name: "MYSQL_DB_NAME"
              value: "DataPlatformMastersAndTransactionsMysqlKube"
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: convert-to-dpfm-invoice-document-from-self-invoice-edi-for-smes
  name: convert-to-dpfm-invoice-document-from-self-invoice-edi-for-smes
spec:
  selector:
    run: convert-to-dpfm-invoice-document-from-self-invoice-edi-for-smes
  type: NodePort
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30928
