package requests

type Header struct {
	ExchangedSelfInvoiceDocumentIdentifier                                           string   `json:"ExchangedSelfInvoiceDocumentIdentifier"`
	ConsolidatedSelfInvoiceDocument                                                  *string  `json:"ConsolidatedSelfInvoiceDocument"`
	ExchangedDocumentContextSpecifiedTransactionIdentifier                           *string  `json:"ExchangedDocumentContextSpecifiedTransactionIdentifier"`
	ExchangedDocumentContextProcessingTransactionDateTime                            *string  `json:"ExchangedDocumentContextProcessingTransactionDateTime"`
	DocumentContextParameterBusinessProcessIdentifier                                *string  `json:"DocumentContextParameterBusinessProcessIdentifier"`
	DocumentContextParameterBusinessProcessValueText                                 *string  `json:"DocumentContextParameterBusinessProcessValueText"`
	DocumentVersionIdentifierOfTransactionProcess                                    *string  `json:"DocumentVersionIdentifierOfTransactionProcess"`
	DocumentVersionIssueDateOfTransactionProcess                                     *string  `json:"DocumentVersionIssueDateOfTransactionProcess"`
	DocumentContextParameterScenarioIdentifier                                       *string  `json:"DocumentContextParameterScenarioIdentifier"`
	DocumentContextParameterScenarioValueText                                        *string  `json:"DocumentContextParameterScenarioValueText"`
	DocumentContextParameterApplicationIdentifier                                    *string  `json:"DocumentContextParameterApplicationIdentifier"`
	DocumentContextParameterApplicationValueText                                     *string  `json:"DocumentContextParameterApplicationValueText"`
	DocumentContextParameterBusinessFieldIdentifier                                  *string  `json:"DocumentContextParameterBusinessFieldIdentifier"`
	DocumentContextParameterBusinessFieldValueText                                   *string  `json:"DocumentContextParameterBusinessFieldValueText"`
	DocumentVersionIdentificationIdentifierOfBusinessFunction                        *string  `json:"DocumentVersionIdentificationIdentifierOfBusinessFunction"`
	DocumentVersionIssueDateOfBusinessFunction                                       *string  `json:"DocumentVersionIssueDateOfBusinessFunction"`
	ExchangedSelfInvoiceDocumentName                                                 *string  `json:"ExchangedSelfInvoiceDocumentName"`
	ExchangedSelfInvoiceDocumentTypeCode                                             *string  `json:"ExchangedSelfInvoiceDocumentTypeCode"`
	ExchangedSelfInvoiceDocumentIssueDate                                            *string  `json:"ExchangedSelfInvoiceDocumentIssueDate"`
	ExchangedSelfInvoiceDocumentPreviousRevisionIdentifier                           *string  `json:"ExchangedSelfInvoiceDocumentPreviousRevisionIdentifier"`
	ExchangedSelfInvoiceDocumentCategoryCode                                         *string  `json:"ExchangedSelfInvoiceDocumentCategoryCode"`
	ExchangedSelfInvoiceDocumentSubtypeCode                                          *string  `json:"ExchangedSelfInvoiceDocumentSubtypeCode"`
	ExchangedSelfInvoiceRequestedResponseTypeCode                                    *string  `json:"ExchangedSelfInvoiceRequestedResponseTypeCode"`
	NoteSelfInvoiceDocumentSubjectText                                               *string  `json:"NoteSelfInvoiceDocumentSubjectText"`
	NoteSelfInvoiceDocumentContentText                                               *string  `json:"NoteSelfInvoiceDocumentContentText"`
	NoteSelfInvoiceDocumentIdentifier                                                *string  `json:"NoteSelfInvoiceDocumentIdentifier"`
	ReferencedDocumentIssuerAssignedIdentifier                                       *string  `json:"ReferencedDocumentIssuerAssignedIdentifier"`
	ReferencedDocumentIssueDate                                                      *string  `json:"ReferencedDocumentIssueDate"`
	ReferencedDocumentRevisionIdentifier                                             *string  `json:"ReferencedDocumentRevisionIdentifier"`
	ReferencedDocumentInformationText                                                *string  `json:"ReferencedDocumentInformationText"`
	ReferencedDocumentTypeCode                                                       *string  `json:"ReferencedDocumentTypeCode"`
	IsAttachmentBinaryObject                                                         *bool    `json:"IsAttachmentBinaryObject"`
	ReferencedDocumentSubtypeCode                                                    *string  `json:"ReferencedDocumentSubtypeCode"`
	SpecifiedBinaryFileIdentifier                                                    *string  `json:"SpecifiedBinaryFileIdentifier"`
	SpecifiedBinaryFileNameText                                                      *string  `json:"SpecifiedBinaryFileNameText"`
	SpecifiedBinaryFileURIIdentifier                                                 *string  `json:"SpecifiedBinaryFileURIIdentifier"`
	SpecifiedBinaryFileMIMECode                                                      *string  `json:"SpecifiedBinaryFileMIMECode"`
	SpecifiedBinaryFileDescriptionText                                               *string  `json:"SpecifiedBinaryFileDescriptionText"`
	TradeSellerIdentifier                                                            *string  `json:"TradeSellerIdentifier"`
	TradeSellerGlobalIdentifier                                                      *string  `json:"TradeSellerGlobalIdentifier"`
	TradeSellerName                                                                  *string  `json:"TradeSellerName"`
	TradeBillFromPartyRegisteredIdentifier                                           *string  `json:"TradeBillFromPartyRegisteredIdentifier"`
	TradeContactSellerIdentifier                                                     *string  `json:"TradeContactSellerIdentifier"`
	TradeContactSellerPersonName                                                     *string  `json:"TradeContactSellerPersonName"`
	TradeContactSellerDepartmentName                                                 *string  `json:"TradeContactSellerDepartmentName"`
	TradeContactSellerPersonIdentifier                                               *string  `json:"TradeContactSellerPersonIdentifier"`
	SellerPhoneNumber                                                                *string  `json:"SellerPhoneNumber"`
	SellerFaxNumber                                                                  *string  `json:"SellerFaxNumber"`
	SellerEmailAddress                                                               *string  `json:"SellerEmailAddress"`
	SellerAddressPostalCode                                                          *string  `json:"SellerAddressPostalCode"`
	SellerAddressLineOne                                                             *string  `json:"SellerAddressLineOne"`
	SellerAddressLineTwo                                                             *string  `json:"SellerAddressLineTwo"`
	SellerAddressLineThree                                                           *string  `json:"SellerAddressLineThree"`
	SellerAddressCountryIdentifier                                                   *string  `json:"SellerAddressCountryIdentifier"`
	TradeBuyerIdentifier                                                             *string  `json:"TradeBuyerIdentifier"`
	TradeBuyerGlobalIdentifier                                                       *string  `json:"TradeBuyerGlobalIdentifier"`
	TradeBuyerName                                                                   *string  `json:"TradeBuyerName"`
	TradeBillToPartyRegisteredIdentifier                                             *string  `json:"TradeBillToPartyRegisteredIdentifier"`
	TradeContactBuyerIdentifier                                                      *string  `json:"TradeContactBuyerIdentifier"`
	TradeContactBuyerPersonName                                                      *string  `json:"TradeContactBuyerPersonName"`
	TradeContactBuyerDepartmentName                                                  *string  `json:"TradeContactBuyerDepartmentName"`
	TradeContactBuyerPersonIdentifier                                                *string  `json:"TradeContactBuyerPersonIdentifier"`
	BuyerTelephoneNumber                                                             *string  `json:"BuyerTelephoneNumber"`
	BuyerFaxNumber                                                                   *string  `json:"BuyerFaxNumber"`
	BuyerEmailAddress                                                                *string  `json:"BuyerEmailAddress"`
	BuyerAddressPostalCode                                                           *string  `json:"BuyerAddressPostalCode"`
	BuyerAddressLineOne                                                              *string  `json:"BuyerAddressLineOne"`
	BuyerAddressLineTwo                                                              *string  `json:"BuyerAddressLineTwo"`
	BuyerAddressLineThree                                                            *string  `json:"BuyerAddressLineThree"`
	BuyerAddressCountryIdentifier                                                    *string  `json:"BuyerAddressCountryIdentifier"`
	ProjectIdentifier                                                                *string  `json:"ProjectIdentifier"`
	ProjectName                                                                      *string  `json:"ProjectName"`
	SupplyChainTradeSettlementTaxCurrencyCode                                        *string  `json:"SupplyChainTradeSettlementTaxCurrencyCode"`
	SupplyChainTradeSettlementSelfInvoiceDocumentCurrencyCode                        *string  `json:"SupplyChainTradeSettlementSelfInvoiceDocumentCurrencyCode"`
	SupplyChainTradeSettlementPaymentCurrencyCode                                    *string  `json:"SupplyChainTradeSettlementPaymentCurrencyCode"`
	TradeBillFromPartyIdentifier                                                     *string  `json:"TradeBillFromPartyIdentifier"`
	TradeBillFromPartyGlobalIdentifier                                               *string  `json:"TradeBillFromPartyGlobalIdentifier"`
	TradeBillFromPartyName                                                           *string  `json:"TradeBillFromPartyName"`
	TradeContactBillFromPartyIdentifier                                              *string  `json:"TradeContactBillFromPartyIdentifier"`
	TradeContactBillFromPartyPersonNameText                                          *string  `json:"TradeContactBillFromPartyPersonNameText"`
	TradeContactBillFromPartyDepartmentNameText                                      *string  `json:"TradeContactBillFromPartyDepartmentNameText"`
	TradeContactBillFromPartyPersonIdentifier                                        *string  `json:"TradeContactBillFromPartyPersonIdentifier"`
	BillFromPartyTelephoneNumber                                                     *string  `json:"BillFromPartyTelephoneNumber"`
	BillFromPartyFaxNumber                                                           *string  `json:"BillFromPartyFaxNumber"`
	BillFromPartyEMailAddress                                                        *string  `json:"BillFromPartyEMailAddress"`
	BillFromPartyAddressPostalCode                                                   *string  `json:"BillFromPartyAddressPostalCode"`
	BillFromPartyAddressLineOne                                                      *string  `json:"BillFromPartyAddressLineOne"`
	BillFromPartyAddressLineTwo                                                      *string  `json:"BillFromPartyAddressLineTwo"`
	BillFromPartyAddressLineThree                                                    *string  `json:"BillFromPartyAddressLineThree"`
	BillFromPartyAddressCountryIdentifier                                            *string  `json:"BillFromPartyAddressCountryIdentifier"`
	TradeSettlementPaymentMeansTypeCode                                              *string  `json:"TradeSettlementPaymentMeansTypeCode"`
	TradeSettlementPaymentMeansInformationText                                       *string  `json:"TradeSettlementPaymentMeansInformationText"`
	TradeSettlementPaymentMeansPaidAmount                                            *float32 `json:"TradeSettlementPaymentMeansPaidAmount"`
	CreditorFinancialAccountName                                                     *string  `json:"CreditorFinancialAccountName"`
	CreditorFinancialAccountProprietaryIdentifier                                    *string  `json:"CreditorFinancialAccountProprietaryIdentifier"`
	CreditorFinancialAccountTypeCode                                                 *string  `json:"CreditorFinancialAccountTypeCode"`
	CreditorFinancialInstitutionName                                                 *string  `json:"CreditorFinancialInstitutionName"`
	CreditorFinancialInstitutionJapanFinancialInstitutionCommonIdentifier            *string  `json:"CreditorFinancialInstitutionJapanFinancialInstitutionCommonIdentifier"`
	BranchFinancialInstitutionIdentifier                                             *string  `json:"BranchFinancialInstitutionIdentifier"`
	BranchFinancialInstitutionName                                                   *string  `json:"BranchFinancialInstitutionName"`
	TradeSettlementFinancialCardIdentifier                                           *string  `json:"TradeSettlementFinancialCardIdentifier"`
	TradeSettlementFinancialCardTypeCode                                             *string  `json:"TradeSettlementFinancialCardTypeCode"`
	TradeSettlementFinancialCardholderName                                           *string  `json:"TradeSettlementFinancialCardholderName"`
	TradeSettlementFinancialCardIssuingCompanyName                                   *string  `json:"TradeSettlementFinancialCardIssuingCompanyName"`
	TradeRefundOrAddAllowanceChargeChargeIndicator                                   *string  `json:"TradeRefundOrAddAllowanceChargeChargeIndicator"`
	TradeRefundOrAddTaxCalculatedAmount                                              *float32 `json:"TradeRefundOrAddTaxCalculatedAmount"`
	TradeRefundOrAddTaxCalculatedRate                                                *float32 `json:"TradeRefundOrAddTaxCalculatedRate"`
	TradeRefundOrAddTaxBasisAmount                                                   *float32 `json:"TradeRefundOrAddTaxBasisAmount"`
	TradeRefundOrAddTaxCategoryCode                                                  *string  `json:"TradeRefundOrAddTaxCategoryCode"`
	TradeTaxCalculatedAmount                                                         *float32 `json:"TradeTaxCalculatedAmount"`
	TradeTaxTypeCode                                                                 *string  `json:"TradeTaxTypeCode"`
	TradeTaxBasisAmount                                                              *float32 `json:"TradeTaxBasisAmount  "`
	TradeTaxCategoryCode                                                             *string  `json:"TradeTaxCategoryCode"`
	TradeTaxCurrencyCode                                                             *string  `json:"TradeTaxCurrencyCode"`
	TradeTaxCategoryNameText                                                         *string  `json:"TradeTaxCategoryNameText"`
	TradeTaxRateApplicablePercent                                                    *float32 `json:"TradeTaxRateApplicablePercent"`
	TradeTaxGrandTotalAmount                                                         *float32 `json:"TradeTaxGrandTotalAmount"`
	TradeTaxCalculationMethodCode                                                    *string  `json:"TradeTaxCalculationMethodCode"`
	TradeTaxLocalTaxSystemIdentifier                                                 *string  `json:"TradeTaxLocalTaxSystemIdentifier"`
	SelfInvoiceDocumentSpecifiedPeriodStartDate                                      *string  `json:"SelfInvoiceDocumentSpecifiedPeriodStartDate"`
	SelfInvoiceDocumentSpecifiedPeriodEndDate                                        *string  `json:"SelfInvoiceDocumentSpecifiedPeriodEndDate"`
	TradePaymentTermsDescriptionText                                                 *string  `json:"TradePaymentTermsDescriptionText"`
	TradePaymentDueDate                                                              *string  `json:"TradePaymentDueDate"`
	TradePaymentTermsTypeCode                                                        *string  `json:"TradePaymentTermsTypeCode"`
	TradeSelfInvoiceDocumentSettlementMonetarySummationChargeTotalAmount             *float32 `json:"TradeSelfInvoiceDocumentSettlementMonetarySummationChargeTotalAmount"`
	TradeSelfInvoiceDocumentSettlementMonetarySummationAllowanceTotalAmount          *float32 `json:"TradeSelfInvoiceDocumentSettlementMonetarySummationAllowanceTotalAmount"`
	TradeSelfInvoiceDocumentSettlementMonetarySummationTaxBasisTotalAmount           *float32 `json:"TradeSelfInvoiceDocumentSettlementMonetarySummationTaxBasisTotalAmount"`
	TradeSelfInvoiceDocumentSettlementMonetarySummationTaxTotalAmount                *float32 `json:"TradeSelfInvoiceDocumentSettlementMonetarySummationTaxTotalAmount"`
	TradeSelfInvoiceDocumentSettlementMonetarySummationGrandTotalAmount              *float32 `json:"TradeSelfInvoiceDocumentSettlementMonetarySummationGrandTotalAmount"`
	TradeSelfInvoiceDocumentSettlementMonetarySummationTotalPrepaidAmount            *float32 `json:"TradeSelfInvoiceDocumentSettlementMonetarySummationTotalPrepaidAmount"`
	TradeSelfInvoiceDocumentSettlementMonetarySummationDuePayableAmount              *float32 `json:"TradeSelfInvoiceDocumentSettlementMonetarySummationDuePayableAmount"`
	TradeSelfInvoiceDocumentSettlementMonetarySummationNetLineTotalAmount            *float32 `json:"TradeSelfInvoiceDocumentSettlementMonetarySummationNetLineTotalAmount"`
	TradeSelfInvoiceDocumentSettlementMonetarySummationIncludingTaxesLineTotalAmount *float32 `json:"TradeSelfInvoiceDocumentSettlementMonetarySummationIncludingTaxesLineTotalAmount"`
	FinancialAdjustmentReasonCode                                                    *string  `json:"FinancialAdjustmentReasonCode"`
	FinancialAdjustmentReasonText                                                    *string  `json:"FinancialAdjustmentReasonText"`
	FinancialAdjustmentActualAmount                                                  *float32 `json:"FinancialAdjustmentActualAmount"`
	FinancialAdjustmentDirectionCode                                                 *string  `json:"FinancialAdjustmentDirectionCode"`
	FixedDocumentReferencedDocumentIssuerAssignedIdentifier                          *string  `json:"FixedDocumentReferencedDocumentIssuerAssignedIdentifier"`
	FixedDocumentReferencedDocumentIssueDate                                         *string  `json:"FixedDocumentReferencedDocumentIssueDate"`
	FixedDocumentReferencedDocumentRevisionIdentifier                                *string  `json:"FixedDocumentReferencedDocumentRevisionIdentifier"`
	FixedDocumentReferencedDocumentTypeCode                                          *string  `json:"FixedDocumentReferencedDocumentTypeCode"`
	FixedDocumentReferencedDocumentSubtypeCode                                       *string  `json:"FixedDocumentReferencedDocumentSubtypeCode"`
	TradelAdjustmentTaxCalculatedAmount                                              *float32 `json:"TradelAdjustmentTaxCalculatedAmount"`
	TradelAdjustmentTaxCalculatedRate                                                *float32 `json:"TradelAdjustmentTaxCalculatedRate"`
	TradelAdjustmentTaxCategoryCode                                                  *string  `json:"TradelAdjustmentTaxCategoryCode"`
	TradeSettlementMonetarySummationAddChargeTotalAmount                             *float32 `json:"TradeSettlementMonetarySummationAddChargeTotalAmount"`
	TradeSettlementMonetarySummationRefundAllowanceTotalAmount                       *float32 `json:"TradeSettlementMonetarySummationRefundAllowanceTotalAmount"`
	TradeSettlementMonetarySummationPreDocumentGrandTotalAmount                      *float32 `json:"TradeSettlementMonetarySummationPreDocumentGrandTotalAmount"`
	TradeSettlementMonetarySummationPreDocumentTotalPrePaidAmount                    *float32 `json:"TradeSettlementMonetarySummationPreDocumentTotalPrePaidAmount"`
	TradeSettlementMonetarySummationDuePayableAmount                                 *float32 `json:"TradeSettlementMonetarySummationDuePayableAmount"`
	DuePayableAmountReferencedDocumentIdentification                                 *string  `json:"DuePayableAmountReferencedDocumentIdentification"`
	DuePayableAmountReferencedDocumentIssueDate                                      *string  `json:"DuePayableAmountReferencedDocumentIssueDate"`
	DuePayableAmountReferencedDocumentRevisionIdentifier                             *string  `json:"DuePayableAmountReferencedDocumentRevisionIdentifier"`
	DuePayableAmountReferencedDocumentInformationText                                *string  `json:"DuePayableAmountReferencedDocumentInformationText"`
	IsAttachmentBinaryObjectReferencedByDuePayableAmount                             *float32 `json:"IsAttachmentBinaryObjectReferencedByDuePayableAmount"`
	DuePayableAmountReferencedDocumentTypeCode                                       *string  `json:"DuePayableAmountReferencedDocumentTypeCode"`
}
